sudo: false
language: php
services: mongodb
before_script:
  - free -m
  - pecl channel-update pecl.php.net
  - sleep 5
  - printf "\n" | pecl install -f --ignore-errors mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
  - wget https://scrutinizer-ci.com/ocular.phar
php:
  - 7.3
  - 7.2
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - composer check
